name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
    build:
        runs-on: windows-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v6 

          - name: Setup python
            uses: actions/setup-python@v6
            with: 
                python-version: '3.13.7'

          - name: Install Poetry
            run: pip install poetry
            
          - name: Install dependencies
            run: |
              poetry install --no-interaction --no-root

          - name: Run tests
            run: poetry run pytest
